version: '3'

services:
  bootstrap:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bootstrapserver
      args:
        P2P_CONFIG: bootstrapserver
    ports:
      - "2233:2233"

  cli1:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cli
      args:
        P2P_CONFIG: cli
    depends_on:
      - bootstrap

  cli2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cli
      args:
        P2P_CONFIG: cli
    depends_on:
      - bootstrap

  
  node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
      args:
        P2P_CONFIG: node
    depends_on:
      - bootstrap
  node2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
      args:
        P2P_CONFIG: node
    depends_on:
      - bootstrap
  node3:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
      args:
        P2P_CONFIG: node
    depends_on:
      - bootstrap
  node4:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
      args:
        P2P_CONFIG: node
    depends_on:
      - bootstrap
  node5:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
      args:
        P2P_CONFIG: node
    depends_on:
      - bootstrap
  node6:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
      args:
        P2P_CONFIG: node
    depends_on:
      - bootstrap
  node7:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
      args:
        P2P_CONFIG: node
    depends_on:
      - bootstrap
  node8:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
      args:
        P2P_CONFIG: node
    depends_on:
      - bootstrap
  node9:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
      args:
        P2P_CONFIG: node
    depends_on:
      - bootstrap
  node10:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
      args:
        P2P_CONFIG: node
    depends_on:
      - bootstrap
