version: '3'

services:
  bootstrap:
    build:
      context: .
      args:
        P2P_CONFIG: bootstrapserver
    ports:
      - "2233:2233"

  cli1:
    build:
      context: .
      args:
        P2P_CONFIG: cli
    depends_on:
      - bootstrap

  cli2:
    build:
      context: .
      args:
        P2P_CONFIG: cli
    depends_on:
      - bootstrap

  # NODE_SERVICES_PLACEHOLDER
